### ISSUE TITLE
Lines longer than 80 characters

### ISSUE THREAD

**Issue by whaleygeek** [AdventuresInMinecraft/code-files#1]
The following lines are longer than 80 characters, and will cause a truncation when the programs.pdf booklet is published:

```
./src//Adventure4/blockHit.py(24): too long:81
./src//Adventure4/blockHit.py(38): too long:90
./src//Adventure4/magicBridge.py(25): too long:87
./src//Adventure4/safeFeet.py(28): too long:89
./src//Adventure4/vanishingBridge.py(33): too long:89

./src//Adventure5/duplicator.py(121): too long:81

./src//Adventure6/LinesCirclesAndSpheres.py(22): too long:81
./src//Adventure6/LinesCirclesAndSpheres.py(23): too long:81
./src//Adventure6/LinesCirclesAndSpheres.py(24): too long:89

./src//Adventure7/AlienInvasion.py(93): too long:91
./src//Adventure7/AlienInvasion.py(95): too long:87
./src//Adventure7/BlockFriend.py(51): too long:84
./src//Adventure7/BlockFriend.py(56): too long:84
./src//Adventure7/BlockFriend.py(59): too long:99
./src//Adventure7/BlockFriend.py(67): too long:91
./src//Adventure7/BlockFriend.py(71): too long:103
./src//Adventure7/BlockFriendRandom.py(53): too long:84
./src//Adventure7/BlockFriendRandom.py(58): too long:84
./src//Adventure7/BlockFriendRandom.py(62): too long:99
./src//Adventure7/BlockFriendRandom.py(79): too long:91
./src//Adventure7/BlockFriendRandom.py(83): too long:103

./src//Adventure8/button2.py(7): too long:84
./src//Adventure8/detonator.py(7): too long:89
./src//Adventure8/detonator.py(48): too long:81
./src//Adventure8/hello.py(7): too long:85
./src//Adventure8/house.py(7): too long:84
./src//Adventure8/imagelist.py(7): too long:88

./src//Adventure9/CraftyCrossing.py(72): too long:91
./src//Adventure9/CraftyCrossing.py(76): too long:95
./src//Adventure9/CraftyCrossing.py(79): too long:83
./src//Adventure9/CraftyCrossing.py(107): too long:109
./src//Adventure9/CraftyCrossing.py(112): too long:92
./src//Adventure9/CraftyCrossingMicrobit.py(76): too long:91
./src//Adventure9/CraftyCrossingMicrobit.py(80): too long:95
./src//Adventure9/CraftyCrossingMicrobit.py(83): too long:83
./src//Adventure9/CraftyCrossingMicrobit.py(111): too long:109
./src//Adventure9/CraftyCrossingMicrobit.py(116): too long:92
```

**Comment by whaleygeek** [comment]
@martinohanlon I have fixed the line lengths in my chapters, could you do the same in yours please?
Here is the list of fixes required:

./src//Adventure6/LinesCirclesAndSpheres.py(22): too long:81
./src//Adventure6/LinesCirclesAndSpheres.py(23): too long:81
./src//Adventure6/LinesCirclesAndSpheres.py(24): too long:89

./src//Adventure7/AlienInvasion.py(93): too long:91
./src//Adventure7/AlienInvasion.py(95): too long:87
./src//Adventure7/BlockFriend.py(51): too long:84
./src//Adventure7/BlockFriend.py(56): too long:84
./src//Adventure7/BlockFriend.py(59): too long:99
./src//Adventure7/BlockFriend.py(67): too long:91
./src//Adventure7/BlockFriend.py(71): too long:103
./src//Adventure7/BlockFriendRandom.py(53): too long:84
./src//Adventure7/BlockFriendRandom.py(58): too long:84
./src//Adventure7/BlockFriendRandom.py(62): too long:99
./src//Adventure7/BlockFriendRandom.py(79): too long:91
./src//Adventure7/BlockFriendRandom.py(83): too long:103

./src//Adventure9/CraftyCrossing.py(72): too long:91
./src//Adventure9/CraftyCrossing.py(76): too long:95
./src//Adventure9/CraftyCrossing.py(79): too long:83
./src//Adventure9/CraftyCrossing.py(107): too long:109
./src//Adventure9/CraftyCrossing.py(112): too long:92

./src//Adventure9/CraftyCrossingMicrobit.py(76): too long:91
./src//Adventure9/CraftyCrossingMicrobit.py(80): too long:95
./src//Adventure9/CraftyCrossingMicrobit.py(83): too long:83
./src//Adventure9/CraftyCrossingMicrobit.py(111): too long:109
./src//Adventure9/CraftyCrossingMicrobit.py(116): too long:92

**Comment by martinohanlon** [comment]
Done - hopefully I got them all anyway!

**Comment by whaleygeek** [comment]
Yep, my check script says it is fine...
![screen shot 2017-09-12 at 21 47 24](https://user-images.githubusercontent.com/4086785/30347463-07923b82-9804-11e7-923e-a37fd8ca9f67.png)

**Comment by whaleygeek** [comment]
Yep, it's much better thanks! LaTeX no longer reports bounding-box errors (zero errors from my check.py script, zero errors from LaTeX). Super!
