### ISSUE TITLE
This program...

### ISSUE THREAD

**Issue by whaleygeek** [AdventuresInMinecraft/code-files#2]
@martinohanlon The programs.pdf builder script automatically strips the first 6 lines from the .py file (the name of the file, blank line, and the 3/4 lines with the link to the book etc.

My programs follow the convention of having a 'This program...' intro at the top. You might like to add that to your programs while you are fixing line lengths, to be consistent.

```
# Adventure 2: rent.py

# From the book: "Adventures in Minecraft", 2nd Edition
# written by David Whale and Martin O'Hanlon, Wiley, 2017
# http://eu.wiley.com/WileyCDA/WileyTitle/productCd-1119439582.html
#
# This program is a game using geo-fencing.
# You are challenged to collect objects from a field in the shortest
# time possible. All the time you are in the field you are charged
# rent. You have to collect/destroy blocks by spending the minimum
# amount of rent. If you stay in the field for too long, your player
# is catapulted up into the sky and out of the field, which makes the
# game harder to play and much more fun!
```

**Comment by martinohanlon** [comment]
added this program headings.

**Comment by whaleygeek** [comment]
Thanks.

Apparently adventure 9 uses abstractles???

```
# This program is a full mini game inside Minecraft called "crafty crossing"
 +# where you have to get to the otherside of an arena while avoiding abstracles
```

**Comment by whaleygeek** [comment]
You might have just invented a new word Mart!!!

http://www.dictionary.com/misspelling?term=abstractles&s=t

**Comment by martinohanlon** [comment]
I've always said that IDE's should come with spell checkers!

**Comment by martinohanlon** [comment]
fixed typo
